_BASE_: "../Base-RCNN-FPN_c6.yaml"
MODEL:
  PIXEL_MEAN: [ 127.5, 127.5, 127.5 ]
  PIXEL_STD: [ 127.5, 127.5, 127.5 ]
  WEIGHTS: "https://layoutlm.blob.core.windows.net/dit/dit-pts/dit-base-224-p16-500k-62d53a.pth"
  VIT:
    NAME: "dit_base_patch16"
SOLVER:
  WARMUP_ITERS: 1000
  IMS_PER_BATCH: 12
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "outputs/maskrcnn_dit_base_c6_publaynet"